language: php
php:
  - '7.1'
  - '7.2'
  - nightly

before_install:
  - composer self-update
  - composer config github-oauth.github.com ${GH_TOKEN}
  - composer validate --no-check-all --ansi

install:
  - composer install
  - chmod -R a+x tests/Scripts/
  - tests/Scripts/setup_app.sh ${GH_TOKEN}
script:
  - vendor/squizlabs/php_codesniffer/bin/phpcs --standard=src/Templates/phpcs/ src
  - vendor/phpmd/phpmd/src/bin/phpmd src text src/Templates/phpmd/rulesets/cleancode src/Templates/phpmd/rulesets/codesize src/Templates/phpmd/rulesets/controversial src/Templates/phpmd/rulesets/design src/Templates/phpmd/rulesets/naming  src/Templates/phpmd/rulesets/unusedcode
  - vendor/phpunit/phpunit/phpunit tests
  - tests/Scripts/run_ccall_in_app.sh
