language: php
php:
  - '7.2'
  - nightly

install:
  - composer install

script:
  - vendor/squizlabs/php_codesniffer/bin/phpcs --standard=src/Templates/phpcs/ src
  - vendor/phpmd/phpmd/src/bin/phpmd src text src/Templates/phpmd/rulesets/cleancode
  - vendor/phpunit/phpunit/phpunit tests